---
name: Azure

# replace with `bosh status --uuid`
director_uuid: a90e23d2-99b4-490d-9f17-64ab630d6999


resources:
  - name: Initiator
    type: git
    source:
      uri: https://github.com/chandrakamarapu/cc-win-worker
      branch: master
  -name: GetBinary
    type: archive
    source:
      uri: https://download.microsoft.com/download/6/8/F/68FE11B8-FAA4-4F8D-8C7D-74DA7F2CFC8C/lis-rpms-4.2.3.tar.gz
  - name: AutomationCode
    type: git
    source:
      uri: https://github.com/chandrakamarapu/azure-linux-automation
      branch: master

jobs:
  - name: CloudTest
    plan:
      - aggregate:
        - get: AutomationCode
        - get: Initiator
          trigger: true
      - task: execute
        privileged: true
        file: Initiator/cc-win.yml
