name: LIS

resources:
  - name: LIS
    type: git
    source:
      uri: https://github.com/LIS/lis-next
      branch: master
  - name: Initiator
    type: git
    source:
      uri: https://github.com/chandrakamarapu/cc-win-worker
      branch: master
  
jobs:
  - name: Build-LIS
    plan:
      - get: LIS
      - get: Initiator
        trigger: true
      - task: execute
        privileged: true
        file: Initiator/build-lis.yml
